name: Simple Local
on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install moment library
        run: npm install --save moment

      - name: Run app.js
        run: node app.js

